from pathlib import Path
import sys
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.config import FIGURE_DIR

st.title("Exploratory Data Analysis (R Visualizations)")
st.markdown("Explore the distributions and relationships in the graduate dataset. These visualizations were generated directly from our R statistical analysis scripts.")

# Path to the figures generated by R
figures_dir = FIGURE_DIR

if figures_dir.exists() and any(figures_dir.iterdir()):
    # Get all png files
    image_files = sorted([f for f in figures_dir.glob("*.png")])
    
    if image_files:
        # Create a user-friendly name mapping
        image_names = {f.stem.replace("_", " ").title(): f for f in image_files}
        
        st.subheader("R Generated Plots")
        selected_name = st.selectbox("Select an Analysis Visualization to View:", list(image_names.keys()))
        selected_file = image_names[selected_name]
        
        st.image(str(selected_file), use_container_width=True, caption=selected_name)
        
        st.divider()
        st.markdown("*Note: If you update the data, please run the `01_cleaning_and_eda.R` script again to regenerate these plots.*")
    else:
        st.warning("No PNG visualizations found in Outputs/figures directory.")
else:
    st.error(f"Could not find the figures directory at: {figures_dir}")
